### ISSUE TITLE
Sober Crashes on Startup

### ISSUE THREAD

**Issue by Tigerko15** [vinegarhq/sober#1181]
### Acknowledgement of checking existent issues

- [x] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.
- [x] I have attached full logs, screenshots, and other relevant info, and understand that if I haven't, my issue will be closed and ignored.

### What problem did you encounter?

Hi, it seems that Sober is unwilling to launch now as of 9:50 Atlantic Time Zone, It was working an hour earlier, but seems to just have stopped working entirely. Not sure if roblox has updated something or if something just randomly broke, No page opens at all

[2025-08-08_21-50-42.log](https://github.com/user-attachments/files/21693882/2025-08-08_21-50-42.log)

**Comment by AlexJonker** [comment]
Same here, worked fine a couple minutes ago. Logs are the same too.

**Comment by snippyrow** [comment]
Same issue for me as well.

**Comment by jujupocacco** [comment]
same here after update it stopped working

**Comment by lunauii** [comment]
> Is anyone with intel having this issue?, my intel laptops are running sober just fine but my pc using AMD isn't.

having issues launching sober on intel laptop here, running endeavouros-hyprland

**Comment by lunauii** [comment]
tried to run as superuser and got this log instead
```
info: app: lifecycle: app_start delta=4.3999869376420975e-05ms
info: app: using C.UTF-8 locale
info: app: lifecycle: logging_started delta=0.48352500004693866ms
info: app: app tag = s057-1868-x86_64-gnu
info: app: lifecycle: update_flags_from_remote_manifest delta=35.53918999992311ms
info: state: using manifest object: {"do_not_retain_swapchain":1,"r1":1,"rbx_texture_semantic":1,"u":1,"use_fast_etc2_vulkan":1}
info: app: lifecycle: fs_init delta=409.0775530000683ms
info: state: starting onboarding flow UI...
info: state:   force_install: no
info: state:   wants_onboarding_home: yes
info: state:   wants_bundle_install: yes
info: state:   do_package_install: yes
info: state:   do_config_standalone: no
info: UIServicesConduit: will execute ui service binary
Authorization required, but no authorization protocol specified
```

**Comment by sakaki91** [comment]
same problem

**Comment by WoondoRU** [comment]
same issue aswell, sober doesn't launch anymore

**Comment by jossmusix** [comment]
Same on Steam Deck.

**Comment by Zeledin** [comment]
same issue on linux pop!os
Config : 
cpu : Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
MemTotal: 8095884 kB
Graphic card : rx 580

latest.log :

info: app: lifecycle: logging_started delta=1.162925999960862ms
info: app: app tag = s057-1868-x86_64-gnu
info: app: lifecycle: update_flags_from_remote_manifest delta=127.57521999999881ms
info: state: using manifest object: {"do_not_retain_swapchain":1,"r1":1,"rbx_texture_semantic":1,"u":1,"use_fast_etc2_vulkan":1}
info: app: lifecycle: fs_init delta=65.77916000003461ms
info: app: lifecycle: check_security delta=1.539827000000514ms
info: app$json: {"product_name":"System Product Name\n","product_version":"System Version\n","type":"device_product_info"}
info: app: lifecycle: core_runtime delta=0.26925599994137883ms
info: app: lifecycle: app_core delta=1.8282929999986663ms

**Comment by barteksiewko40-create** [comment]
i also have this bug

**Comment by gattino093** [comment]
same here on steaam deck

info: app: lifecycle: app_start delta=7.003545761108398e-05ms
info: app: using C.UTF-8 locale
info: app: lifecycle: logging_started delta=1.2258029580116272ms
info: app: app tag = s057-1868-x86_64-gnu
info: app: lifecycle: update_flags_from_remote_manifest delta=108.55137699842453ms
info: state: using manifest object: {"do_not_retain_swapchain":1,"r1":1,"rbx_texture_semantic":1,"u":1,"use_fast_etc2_vulkan":1}
info: app: lifecycle: fs_init delta=112.55857002735138ms
info: app: lifecycle: check_security delta=1.1056609749794006ms
info: app$json: {"product_name":"Jupiter\n","product_version":"1\n","type":"device_product_info"}
info: app: lifecycle: core_runtime delta=0.17878204584121704ms
info: app: lifecycle: app_core delta=1.853279948234558ms
info: discord_rpc: RPC connected

**Comment by FireMatt1** [comment]
same issue here

**Comment by WinSer2003** [comment]
got the same problem

**Comment by AlexJonker** [comment]
This build in the official VinegarHQ discord server works fine https://discord.com/channels/1069506340973707304/1403567294218768395/1403616212046581780

This is the server invite link: https://discord.gg/dzdzZ6Pps2

**Comment by V3L0C1T13S** [comment]
Fixed in 1.5.3. Run `flatpak update`

**Comment by luisalvarado** [comment]
Still happening on 1.5.3 as confirmed in 3 computers today. They all received the 1.5.3 update and crashed. I did delete the sober folder and the installation process starts fine, but after the installation finishes, the app opens for a second then crashes again.

Here is one of the outputs basically just imagine all 3 with the same issue:

[robloxCrash.log](https://github.com/user-attachments/files/21707911/robloxCrash.log)

**Comment by V3L0C1T13S** [comment]
> Still happening on 1.5.3 as confirmed in 3 computers today. They all received the 1.5.3 update and crashed. I did delete the sober folder and the installation process starts fine, but after the installation finishes, the app opens for a second then crashes again.

We did just fix another crash affecting some users, although I'm not sure if the build has hit Flathub stable yet. If you wanna give it a go, run `flatpak install --user https://dl.flathub.org/build-repo/203092/org.vinegarhq.Sober.flatpakref`.

**Comment by quest99812** [comment]
i hope that the patch will eventually release for this error. I cant play roblox for such a long time now.

**Comment by ERROR2401** [comment]
I'm experiencing this bug too, as of the latest update a couple hours ago.

**Comment by ranidspace** [comment]
Still experiencing as well, with the flatpakref, but in a very odd way.

I use Hyprland with UWSM. My terminal is kitty and my application launcher is rofi-wayland, and my shell is zsh.

Launching from kitty, `flatpak run org.vinegarhq.Sober` works.

Launching from command line `rofi -show drun -run-command "uwsm-app -- {cmd}"` and then selecting Sober also works.

Using that either of those two commands set up as a keybind does not, as well as including `kitty --hold --` before it to view the stdout. It halts at the same `info: app: lifecycle: app_core` line.

I've determined that it doesn't matter whether kitty, rofi, or sober is launched as a UWSM app or not at least.

However, I noticed that if rofi/sober is launched as kitty args, my zsh profile isn't sourced until after, and then if I run the exact command again within the exact same kitty window after it failed, it works.

Launching ZSH with default configuration works, so it's not something I have configured. Launching from bash or fish, or even python using `subprocess.run(["/usr/bin/flatpak", "run", "org.vinegarhq.Sober"])` works too.

My guess is that it only breaks on my system if it's directly invoked, and not from a shell.

HOWEVER, it DOES run properly if I instead run `kitty --hold -- flatpak run org.vinegarhq.Sober` FROM an existing kitty window. (the profile seems to gets loaded after as well). The issue only appears to be if it's launched directly from a keybind.

I have no idea what this could even be causing this. Plus for most people it seems to be different. My partner has a very similar setup to mine, and he's unable to launch it at all. No clue what it could be, but if you're able to recreate this maybe it would help idk

**Comment by Luweegeeman** [comment]
> # Statement Regarding Startup Crashes
> We're incredibly sorry for the recent stability issues. As Roblox is a fast-moving target, recently even more so, we have to constantly adapt to maintain Linux support. As you can clearly see, sometimes we miss the mark, leading to an incredibly negative experience.
> 
> Once again, we're sorry. We're working all hands on deck to provide a patch that matches our standards for safety & quality (which recently we've unfortunately failed to meet up to).
> 
> ## Temporary Solution: Downgrade
> Use the command below (elevate if needed) to downgrade Sober:
> 
> ```
> flatpak update --commit=51d7392004a94628e9bfdb6300fb724fc5923d16fe3e8556ad3ea617190c6239 org.vinegarhq.Sober
> ```

Thanks for dropping the Downgrade! Can confirm this helped.

**Comment by StarKiller123321** [comment]
> # Statement Regarding Startup Crashes
> 
> We're incredibly sorry for the recent stability issues. As Roblox is a fast-moving target, recently even more so, we have to constantly adapt to maintain Linux support. As you can clearly see, sometimes we miss the mark, leading to an incredibly negative experience.
> 
> Once again, we're sorry. We're working all hands on deck to provide a patch that matches our standards for safety & quality (which recently we've unfortunately failed to meet up to).
> ## Temporary Solution: Downgrade
> 
> Use the command below (elevate if needed) to downgrade Sober:
> 
> ```
> flatpak update --commit=51d7392004a94628e9bfdb6300fb724fc5923d16fe3e8556ad3ea617190c6239 org.vinegarhq.Sober
> ```

i copied this i to terminal but an error came up, "There were one or more errors"

**Comment by k1yrix** [comment]
> i copied this i to terminal but an error came up, "There were one or more errors"

did it say something about running as root?

**Comment by B0Tz1337** [comment]
> > root permission or smth
> 
> run the downgrade command with `sudo` in front of it

sudo flatpak update --commit=51d7392004a94628e9bfdb6300fb724fc5923d16fe3e8556ad3ea617190c6239 org.vinegarhq.Sober 

I got Sudo helped!

**Comment by StarKiller123321** [comment]
> sudo flatpak update --commit=51d7392004a94628e9bfdb6300fb724fc5923d16fe3e8556ad3ea617190c6239 org.vinegarhq.Sober

whats the "password for deck"

**Comment by epicsteamdecker** [comment]
> > > > sudo flatpak update --commit=51d7392004a94628e9bfdb6300fb724fc5923d16fe3e8556ad3ea617190c6239 org.vinegarhq.Sober
> > > 
> > > 
> > > whats the "password for deck"
> > 
> > 
> > did u forget ur sudo password ur lowk cooked
> 
> what is the sudo password idk

try Decky! if that dont work i cant help gng... if u havent set one up yet try command `passwd` in konsle

**Comment by StarKiller123321** [comment]
> > > > > sudo flatpak update --commit=51d7392004a94628e9bfdb6300fb724fc5923d16fe3e8556ad3ea617190c6239 org.vinegarhq.Sober
> > > > 
> > > > 
> > > > whats the "password for deck"
> > > 
> > > 
> > > did u forget ur sudo password ur lowk cooked
> > 
> > 
> > what is the sudo password idk
> 
> try Decky! if that dont work i cant help gng... if u havent set one up yet try command `passwd` in konsle

IT WORKED THX SO MUCH TO YOU ALL

**Comment by luisalvarado** [comment]
Confirmed in 4 computers. Works perfectly in all.

**Comment by quest99812** [comment]
Thanks devs! I can finally play roblox like i used to

**Comment by darkninja2006** [comment]
i reinstalled, ran flatpak upgrade, etc. but still get 
info: app: lifecycle: app_start delta=4.999997327104211e-05ms
info: app: using C.UTF-8 locale
info: app: lifecycle: logging_started delta=0.7696080000023358ms
info: app: app tag = s061-1868-x86_64-gnu
info: app: lifecycle: update_flags_from_remote_manifest delta=40.83705500001088ms
info: state: using manifest object: {"do_not_retain_swapchain":1,"r1":1,"rbx_texture_semantic":1,"u":1,"use_fast_etc2_vulkan":1}
info: app: lifecycle: fs_init delta=247.8554320000112ms
info: app: lifecycle: check_security delta=8.27893899998162ms
info: app$json: {"product_name":"MS-7E26\n","product_version":"1.0\n","type":"device_product_info"}
info: app: lifecycle: core_runtime delta=0.09887899999739602ms
info: app: lifecycle: app_core delta=0.7273329999879934ms
  ~ 

**Comment by Vexcited** [comment]
Still happening for me as of today on Arch Linux with latest Flatpak version,

```
info: app: lifecycle: app_start delta=4.999997327104211e-05ms
info: app: using C.UTF-8 locale
info: app: lifecycle: logging_started delta=0.7090409999946132ms
info: app: app tag = s061-1868-x86_64-gnu
info: app: lifecycle: update_flags_from_remote_manifest delta=58.123047000030056ms
info: state: using manifest object: {"do_not_retain_swapchain":1,"r1":1,"rbx_texture_semantic":1,"u":1,"use_fast_etc2_vulkan":1}
info: app: lifecycle: fs_init delta=72.35036799998488ms
info: state: starting onboarding flow UI...
info: state:   force_install: no
info: state:   wants_onboarding_home: yes
info: state:   wants_bundle_install: yes
info: state:   do_package_install: yes
info: state:   do_config_standalone: no
info: UIServicesConduit: will execute ui service binary
info: state: downloading Roblox from update service...
info: state: installed Roblox using update service
info: UIServicesConduit: waiting for ui service to exit...
info: UIServicesConduit: ui service exited
info: app: lifecycle: check_security delta=11361.648556999979ms
info: app$json: {"product_name":"ASUS TUF Gaming A15 FA507NUR_FA507NUR\n","product_version":"1.0\n","type":"device_product_info"}
info: app: lifecycle: core_runtime delta=0.17902499996125698ms
info: app: lifecycle: app_core delta=1.0861390000209212ms
```

and it closes... any workaround?

**Comment by Taboulet** [comment]
It's back ;(

**Comment by Taboulet** [comment]
1.5.3 hotfix : 87a106ab0135a20da1e9e37d7b5dd0f67e9deadbf5f6b58af56783e9c9d5a8a3
1.5.3 first release : c9cf75f3b275888dc4bf5a999fa773566df5dda3d669e1add92b7ba1cc113992
1.5.2 : fa83316b5a7a4645c195c13ae10789b17d449486765559413438c481524526bd

For me none of these fixed it but i managed to launch Sober when using 1.5.2 and i was at the login page but i tried to check if 1.5.3 also worked but then it never worked again

**Comment by RaphVSSR** [comment]
"Outdated" :/

**Comment by lain009-gif** [comment]
plz do an update i cant play femboy tycoon :(

**Comment by 17OhKlahoma** [comment]
Hello. As of today same issue is happening.
`info: app: lifecycle: app_start delta=0.00019899941980838776ms
info: app: using C.UTF-8 locale
info: app: lifecycle: logging_started delta=2.5691209994256496ms
info: app: app tag = s061-1868-x86_64-gnu
info: app: lifecycle: update_flags_from_remote_manifest delta=190.11646600067616ms
info: state: using manifest object: {"do_not_retain_swapchain":1,"r1":1,"rbx_texture_semantic":1,"u":1,"use_fast_etc2_vulkan":1}
info: app: lifecycle: fs_init delta=530.7588919997215ms
info: app: lifecycle: check_security delta=6.321968000382185ms
info: app$json: {"product_name":"Aspire E5-553G\n","product_version":"V1.31\n","type":"device_product_info"}
info: app: lifecycle: core_runtime delta=0.5024999994784594ms
info: app: lifecycle: app_core delta=5.204115999862552ms
`
Running on Linux Mint if that helps.

**Comment by Melan3000** [comment]
Im having the same issue too it just instantly closes whenever I open sober. 

info: app: lifecycle: logging_started delta=1.0442620001267642ms
info: app: app tag = s063-1872-x86_64-gnu
info: app: os release: Fedora Linux
info: app: lifecycle: update_flags_from_remote_manifest delta=51.563420000020415ms
info: state: using manifest object: {"do_not_retain_swapchain":1,"r1":1,"rbx_texture_semantic":1,"u":1,"use_fast_etc2_vulkan":1}
info: app: lifecycle: fs_init delta=130.752179000061ms
info: app: using config: {
    "allow_gamepad_permission": false,
    "bring_back_oof": false,
    "close_on_leave": false,
    "discord_rpc_enabled": true,
    "enable_gamemode": true,
    "enable_hidpi": false,
    "fflags": {
        "FFlagExample": true
    },
    "server_location_indicator_enabled": false,
    "touch_mode": "off",
    "use_console_experience": false,
    "use_libsecret": false,
    "use_opengl": false
}
info: app: lifecycle: check_security delta=1.6807750000152737ms
info: app$json: {"product_name":"Swift SF314-59\n","product_version":"V1.09\n","type":"device_product_info"}
info: app: lifecycle: core_runtime delta=0.08881899993866682ms
info: app: lifecycle: app_core delta=7.760707000037655ms
info: app: lifecycle: sdl_init delta=735.8032129998319ms
info: app: trying video backend preference: wayland,x11
info: app: using video backend: wayland
info: app: trying audio subsystem pulseaudio
info: app: using audio subsystem pulseaudio
info: app: lifecycle: global_window_init delta=104.45083800004795ms
info: app: lifecycle: gamemode_init delta=73.17099700006656ms
info: app: lifecycle: interface_init delta=39.80908799986355ms
debug: JNIMain: TelemetryProtocol::setProcessTimeOverride: 1433
info: rbx.JNIRobloxSettings: Setting default app policy file: content/guac/defaultConfigs/GuacDefaultPolicy-GlobalDist.json
info: Roblox: 2025-09-04T02:55:45.559Z,0.559709,1b29680,6 [FLog::AndroidGLView] nativeInitClientSettings
info: Roblox: 2025-09-04T02:55:45.567Z,0.567755,1b29680,6 [FLog::Output] LoadClientSettingsFromLocal: "Do not use this file. Use "/home/melan3000/.var/app/org.vinegarhq.Sober/config/sober/config.json" instead.
"
info: Roblox: 2025-09-04T02:55:45.567Z,0.567789,1b29680,6 [FLog::Error] Error loading settings: [0: Invalid value.] settings size = 107
info: Roblox: 2025-09-04T02:55:45.569Z,0.569036,1b29680,6 [FLog::AndroidGLView] nativePostClientSettingsLoadedInitialization3
info: Roblox: 2025-09-04T02:55:45.580Z,0.580680,1b29680,6,Info [FLog::AppMemUsageStatus] 3698476798
info: Roblox: 2025-09-04T02:55:45.580Z,0.580778,1b29680,6 [FLog::ClientRunInfo] RobloxGitHash: 84a28ed938d4cf1fb961d5cf9164991e6870de0e
info: Roblox: 2025-09-04T02:55:45.580Z,0.580792,1b29680,6 [FLog::ClientRunInfo] The base url is https://www.roblox.com/
info: Roblox: 2025-09-04T02:55:45.580Z,0.580800,1b29680,6 [FLog::ClientRunInfo] The channel is production
info: Roblox: 2025-09-04T02:55:45.581Z,0.581369,1b29680,6,Critical [DFLog::Mimalloc] Mimalloc integration detected, settings:
info: Roblox: 2025-09-04T02:55:45.581Z,0.581385,1b29680,6,Critical [DFLog::Mimalloc] mi_option_show_errors=1
info: Roblox: 2025-09-04T02:55:45.581Z,0.581391,1b29680,6,Info [DFLog::Mimalloc] mi_option_show_stats=0
info: Roblox: 2025-09-04T02:55:45.581Z,0.581396,1b29680,6,Info [DFLog::Mimalloc] mi_option_verbose=0
info: Roblox: 2025-09-04T02:55:45.581Z,0.581401,1b29680,6,Critical [DFLog::Mimalloc] mi_option_eager_commit=0
info: Roblox: 2025-09-04T02:55:45.581Z,0.581405,1b29680,6,Info [DFLog::Mimalloc] mi_option_arena_eager_commit=2
info: Roblox: 2025-09-04T02:55:45.581Z,0.581409,1b29680,6,Info [DFLog::Mimalloc] mi_option_purge_decommits=1
info: Roblox: 2025-09-04T02:55:45.581Z,0.581412,1b29680,6,Info [DFLog::Mimalloc] mi_option_allow_large_os_pages=0
info: Roblox: 2025-09-04T02:55:45.581Z,0.581416,1b29680,6,Info [DFLog::Mimalloc] mi_option_reserve_huge_os_pages=0
info: Roblox: 2025-09-04T02:55:45.581Z,0.581422,1b29680,6,Info [DFLog::Mimalloc] mi_option_reserve_huge_os_pages_at=-1
info: Roblox: 2025-09-04T02:55:45.581Z,0.581434,1b29680,6,Info [DFLog::Mimalloc] mi_option_reserve_os_memory=0
info: Roblox: 2025-09-04T02:55:45.581Z,0.581439,1b29680,6,Info [DFLog::Mimalloc] mi_option_deprecated_segment_cache=0
info: Roblox: 2025-09-04T02:55:45.581Z,0.581443,1b29680,6,Info [DFLog::Mimalloc] mi_option_deprecated_page_reset=0
info: Roblox: 2025-09-04T02:55:45.581Z,0.581447,1b29680,6,Info [DFLog::Mimalloc] mi_option_abandoned_page_purge=0
info: Roblox: 2025-09-04T02:55:45.581Z,0.581450,1b29680,6,Critical [DFLog::Mimalloc] mi_option_purge_delay=0
info: Roblox: 2025-09-04T02:55:45.581Z,0.581454,1b29680,6,Info [DFLog::Mimalloc] mi_option_deprecated_segment_reset=0
info: Roblox: 2025-09-04T02:55:45.581Z,0.581458,1b29680,6,Info [DFLog::Mimalloc] mi_option_eager_commit_delay=1
info: Roblox: 2025-09-04T02:55:45.581Z,0.581462,1b29680,6,Info [DFLog::Mimalloc] mi_option_use_numa_nodes=0
info: Roblox: 2025-09-04T02:55:45.581Z,0.581466,1b29680,6,Info [DFLog::Mimalloc] mi_option_disallow_os_alloc=0
info: Roblox: 2025-09-04T02:55:45.581Z,0.581469,1b29680,6,Info [DFLog::Mimalloc] mi_option_os_tag=100
info: Roblox: 2025-09-04T02:55:45.581Z,0.581474,1b29680,6,Info [DFLog::Mimalloc] mi_option_max_errors=32
info: Roblox: 2025-09-04T02:55:45.581Z,0.581478,1b29680,6,Info [DFLog::Mimalloc] mi_option_max_warnings=32
info: Roblox: 2025-09-04T02:55:45.581Z,0.581482,1b29680,6,Info [DFLog::Mimalloc] mi_option_deprecated_max_segment_reclaim=10
info: Roblox: 2025-09-04T02:55:45.581Z,0.581486,1b29680,6,Info [DFLog::Mimalloc] mi_option_destroy_on_exit=0
info: Roblox: 2025-09-04T02:55:45.581Z,0.581490,1b29680,6,Info [DFLog::Mimalloc] mi_option_arena_reserve=1048576
info: Roblox: 2025-09-04T02:55:45.581Z,0.581494,1b29680,6,Info [DFLog::Mimalloc] mi_option_arena_purge_mult=1
info: Roblox: 2025-09-04T02:55:45.581Z,0.581498,1b29680,6,Info [DFLog::Mimalloc] mi_option_deprecated_purge_extend_delay=1
info: Roblox: 2025-09-04T02:55:45.581Z,0.581502,1b29680,6,Info [DFLog::Mimalloc] mi_option_disallow_arena_alloc=0
info: Roblox: 2025-09-04T02:55:45.581Z,0.581507,1b29680,6,Info [DFLog::Mimalloc] mi_option_retry_on_oom=400
info: Roblox: 2025-09-04T02:55:45.581Z,0.581510,1b29680,6,Info [DFLog::Mimalloc] mi_option_visit_abandoned=0
info: Roblox: 2025-09-04T02:55:45.581Z,0.581515,1b29680,6,Info [DFLog::Mimalloc] mi_option_guarded_min=0
info: Roblox: 2025-09-04T02:55:45.581Z,0.581518,1b29680,6,Info [DFLog::Mimalloc] mi_option_guarded_max=1073741824
info: Roblox: 2025-09-04T02:55:45.581Z,0.581522,1b29680,6,Info [DFLog::Mimalloc] mi_option_guarded_precise=0
info: Roblox: 2025-09-04T02:55:45.581Z,0.581530,1b29680,6,Info [DFLog::Mimalloc] mi_option_guarded_sample_rate=0
info: Roblox: 2025-09-04T02:55:45.581Z,0.581538,1b29680,6,Info [DFLog::Mimalloc] mi_option_guarded_sample_seed=0
info: Roblox: 2025-09-04T02:55:45.581Z,0.581542,1b29680,6,Info [DFLog::Mimalloc] mi_option_page_reclaim_on_free=0
info: Roblox: 2025-09-04T02:55:45.581Z,0.581546,1b29680,6,Info [DFLog::Mimalloc] mi_option_page_full_retain=2
info: Roblox: 2025-09-04T02:55:45.581Z,0.581550,1b29680,6,Info [DFLog::Mimalloc] mi_option_page_max_candidates=4
info: Roblox: 2025-09-04T02:55:45.581Z,0.581555,1b29680,6,Info [DFLog::Mimalloc] mi_option_max_vabits=0
info: Roblox: 2025-09-04T02:55:45.581Z,0.581559,1b29680,6,Info [DFLog::Mimalloc] mi_option_pagemap_commit=0
info: Roblox: 2025-09-04T02:55:45.581Z,0.581563,1b29680,6,Info [DFLog::Mimalloc] mi_option_page_commit_on_demand=0
info: Roblox: 2025-09-04T02:55:45.581Z,0.581566,1b29680,6,Info [DFLog::Mimalloc] mi_option_page_max_reclaim=-1
info: Roblox: 2025-09-04T02:55:45.581Z,0.581570,1b29680,6,Info [DFLog::Mimalloc] mi_option_page_cross_thread_max_reclaim=32
info: Roblox: 2025-09-04T02:55:45.581Z,0.581857,1b29680,6,Info [FLog::AppMemUsageStatus] 923286370
info: device_params_impls$json: {"device_memory_class_mib":2048,"device_memory_mib":7722,"is_low_ram_device":false,"type":"memory_params"}
info: rbx.AppBridgeV2: nativeAppBridgeAppStart_original:
debug: rbx.AppBridgeV2: nativeAppBridgeV2Init:
info: Roblox: 2025-09-04T02:55:45.593Z,0.593423,9f53b6c0,6 [FLog::SingleSurfaceApp] initializeWithAppStarter
info: Roblox: 2025-09-04T02:55:45.593Z,0.593451,9f53b6c0,6 [FLog::SingleSurfaceApp] initializeSingleton
info: Roblox: 2025-09-04T02:55:45.593Z,0.593641,9f53b6c0,6 [FLog::Output] setAssetFolder /home/melan3000/.var/app/org.vinegarhq.Sober/data/sober/assets/content/
info: Roblox: 2025-09-04T02:55:45.593Z,0.593718,9f53b6c0,6 [FLog::Output] setExtraAssetFolder /home/melan3000/.var/app/org.vinegarhq.Sober/data/sober/assets/ExtraContent
info: Roblox: 2025-09-04T02:55:45.593Z,0.593808,9f53b6c0,6 [FLog::Output] Evaluating deferred inferred crashes
info: Roblox: 2025-09-04T02:55:45.593Z,0.593936,9f53b6c0,6 [FLog::SingleSurfaceApp] registerForForceOTAUpdateAvailableConnection stage = 0
info: Roblox: 2025-09-04T02:55:45.595Z,0.595445,9f53b6c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Load configs for user key: app:14169667683193958462
info: Roblox: 2025-09-04T02:55:45.595Z,0.595998,9f53b6c0,6 [FLog::SingleSurfaceApp] setStage: (stage:Native)
info: Roblox: 2025-09-04T02:55:45.596Z,0.596016,9f53b6c0,6,Warning [FLog::SingleSurfaceApp] instantiate controllers
info: Roblox: 2025-09-04T02:55:45.596Z,0.596022,9f53b6c0,6 [FLog::SurfaceController] SurfaceController[_:1]::SurfaceController, count: 1
info: Roblox: 2025-09-04T02:55:45.596Z,0.596028,9f53b6c0,6,Warning [FLog::SingleSurfaceApp] instantiate experience coordinator
info: Roblox: 2025-09-04T02:55:45.596Z,0.596096,9f53b6c0,6,Info [DFLog::CoordinatorMemoryPressure] Setting memory pressure threshold to none
info: Roblox: 2025-09-04T02:55:45.597Z,0.597486,9f53b6c0,6,Info [FLog::PerformanceControlUtil] PerformanceControlUtil: registered single surface tunable (id=0)
info: Roblox: 2025-09-04T02:55:45.597Z,0.597510,9f53b6c0,6,Info [FLog::CrossExperienceVoiceController] CrossExperienceVoiceController::CrossExperienceVoiceController() constructor
info: Roblox: 2025-09-04T02:55:45.597Z,0.597530,9f53b6c0,6,Info [FLog::PerformanceControlUtil] PerformanceControlUtil: registered single surface tunable (id=1)
info: app: lifecycle: interface_start delta=346.06318400008604ms
info: Roblox: 2025-09-04T02:55:45.597Z,0.597711,9f53b6c0,6 [FLog::SingleSurfaceApp] initializeLuaAppWithLoggedInUser: (stage:Native).
info: Roblox: 2025-09-04T02:55:45.597Z,0.597719,9f53b6c0,6 [FLog::SingleSurfaceApp] applyLocale
info: Roblox: 2025-09-04T02:55:45.609Z,0.609099,9f53b6c0,6 [FLog::DataModelPatchConfigurer] [_UniversalAppPatch] Load configs for user key: app:14169667683193958462
info: Roblox: 2025-09-04T02:55:45.609Z,0.609264,9f53b6c0,6 [FLog::DataModelPatchConfigurer] [_UniversalAppPatch] Retrieving patch
info: Roblox: 2025-09-04T02:55:45.609Z,0.609274,9f53b6c0,6 [FLog::DataModelPatchConfigurer] getCachedPatch DataModelPatchConfig : type=1, assetId=118593852151835, assetVersion=3369, maxAppVersion=687, localAssetURI=rbxasset://models/UniversalApp/UniversalApp.rbxm
info: Roblox: 2025-09-04T02:55:45.609Z,0.609284,9f53b6c0,6 [FLog::DataModelPatchConfigurer] getCachedPatch : numAttempts=10
info: Roblox: 2025-09-04T02:55:45.609Z,0.609327,9f53b6c0,6 [FLog::DataModelPatchConfigurer] getCachedPatch : contentId=rbxasset://models/UniversalApp/UniversalApp.rbxm
info: Roblox: 2025-09-04T02:55:45.609Z,0.609334,9f53b6c0,6 [FLog::DataModelPatchConfigurer] getCachedPatch : get patch from content provider for Model
info: Roblox: 2025-09-04T02:55:45.609Z,0.609380,9f53b6c0,6 [FLog::DataModelPatchConfigurer] deserializeAndVerifyPatch with blake3
info: Roblox: 2025-09-04T02:55:45.810Z,0.810816,9f53b6c0,6,Warning [DFLog::BootcampCLI161265Log] Hello world ...!
info: Roblox: 2025-09-04T02:55:45.810Z,0.810851,9f53b6c0,6,Warning [DFLog::BootcampCLI158749Log] hey world
info: Roblox: 2025-09-04T02:55:45.810Z,0.810857,9f53b6c0,6,Warning [FLog::Output] Hello world!!!
info: Roblox: 2025-09-04T02:55:45.810Z,0.810863,9f53b6c0,6,Warning [DFLog::BootcampCLI149079Log] Hello world?
info: Roblox: 2025-09-04T02:55:45.810Z,0.810868,9f53b6c0,6,Warning [DFLog::BootcampCLI154937Log] I love roblox. Roblox is life
info: Roblox: 2025-09-04T02:55:45.810Z,0.810872,9f53b6c0,6,Warning [DFLog::BootcampCLI156010Log] Hello there, world
info: Roblox: 2025-09-04T02:55:45.810Z,0.810877,9f53b6c0,6,Warning [DFLog::BootcampCLI162827Log] Hello world, this is the last time I onboard!
info: Roblox: 2025-09-04T02:55:45.810Z,0.810881,9f53b6c0,6,Warning [DFLog::BootcampCLI161528Log] Hello folks~
info: Roblox: 2025-09-04T02:55:45.810Z,0.810885,9f53b6c0,6,Warning [DFLog::BootcampCLI163626Log] Hello world :)
info: rbx.AppBridgeV2: nativeAppBridgeAppStart: StartupController finished starting: stage = 2, BTID = 0, upgradeStatus = 3.
info: Roblox: 2025-09-04T02:55:45.819Z,0.819193,9f53b6c0,6 [FLog::SingleSurfaceApp] setStage: (stage:InitializedLuaApp)
info: app: lifecycle: pre_main_loop delta=221.53582100011408ms
info: app: lifecycle: enter_main_loop delta=0.007272999966517091ms
debug: rbx.AppBridgeV2: nativeAppBridgeV2UpdateSurfaceApp:
debug: rbx.AppBridgeV2: nativeAppBridgeV2UpdateSurfaceApp: Created ANativeWindow 0x4cc04498340 (ID:1)
info: Roblox: 2025-09-04T02:55:45.822Z,0.822468,9f53b6c0,6 [FLog::SingleSurfaceApp] updateSurfaceLuaApp: (stage:InitializedLuaApp)
info: Roblox: 2025-09-04T02:55:45.822Z,0.822489,9f53b6c0,6,Warning [FLog::SurfaceController] SurfaceController[_:1]::update.
debug: rbx.AppBridgeV2: nativeAppBridgeV2UpdateSurfaceGameNew:
debug: rbx.AppBridgeV2: nativeAppBridgeV2UpdateSurfaceGameNew: Same native window 0x4cc04498340. No need to do anything!
info: Roblox: 2025-09-04T02:55:45.833Z,0.833513,9f53b6c0,6 [FLog::SingleSurfaceApp] updateSurfaceUGCGame: (stage:InitializedLuaApp).
info: Roblox: 2025-09-04T02:55:45.833Z,0.833575,9e2366c0,6 [FLog::Output] Info: DataModel Loading rbxasset://places/Mobile.rbxl
info: Roblox: 2025-09-04T02:55:45.850Z,0.850652,9e2366c0,6 [FLog::DataModelPatchConfigurer] OTAPollingEnabled set to: false
info: Roblox: 2025-09-04T02:55:45.894Z,0.894056,9e2366c0,6 [FLog::DataModelPatchConfigurer] [discovery-ota] Load configs for user key: app:14169667683193958462
info: Roblox: 2025-09-04T02:55:45.894Z,0.894291,9e2366c0,6 [FLog::DataModelPatchConfigurer] [discovery-ota] Retrieving patch
info: Roblox: 2025-09-04T02:55:45.894Z,0.894305,9e2366c0,6 [FLog::DataModelPatchConfigurer] getCachedPatch DataModelPatchConfig : type=1, assetId=16639814581, assetVersion=4918, maxAppVersion=687, localAssetURI=
info: Roblox: 2025-09-04T02:55:45.966Z,0.966238,9e2366c0,6,Info [FLog::AudioFocusManager] AudioFocusManager::AudioFocusManager() constructor
info: Roblox: 2025-09-04T02:55:45.966Z,0.966277,9e2366c0,6,Info [FLog::AudioFocusService] AudioFocusService::AudioFocusService() constructor
info: Roblox: 2025-09-04T02:55:45.966Z,0.966287,9e2366c0,6,Info [FLog::AudioFocusService] AudioFocusService onServiceProvider invokation
info: Roblox: 2025-09-04T02:55:45.966Z,0.966292,9e2366c0,6,Info [FLog::AudioFocusService] AudioFocusService::AudioFocusService() onServiceProvider setup
info: app_interface$json: {"place_id":"0","type":"game_loaded"}
info: Roblox: 2025-09-04T02:55:46.167Z,1.167887,9c9326c0,12 [DFLog::HttpTraceError] CURLINFO_OS_ERRNO: 111 Connection refused
info: Roblox: 2025-09-04T02:55:46.167Z,1.167922,9c9326c0,12 [DFLog::HttpTraceError] CURLOPT_ERRORBUFFER: Failed to connect to localhost port 5051 after 2 ms: Could not connect to server
info: Roblox: 2025-09-04T02:55:46.168Z,1.168074,9c1316c0,6 [DFLog::WebSocketTraceError] ws: 0 url: http://localhost:5051 error: HttpError: ConnectFail
info: Roblox: 2025-09-04T02:55:46.168Z,1.168107,9c1316c0,12 [DFLog::HttpTraceError] HttpResponse(#4 0x7f27c13a06b0) time:2.7ms (net:2.6ms callback:0.0ms timeInRetryQueue:0.0ms) error:3 message:HttpError: ConnectFail url:{ "http://localhost:5051" } ip: external:0 numberOfTimesRetried:0
info: Roblox: 2025-09-04T02:55:46.172Z,1.172770,9e4386c0,6 [FLog::Warning] Warning: Unable to fetch completed survey ids from app storage  
info: Roblox: 2025-09-04T02:55:46.261Z,1.261088,9e2366c0,6,Warning [DFLog::DMNotificationMonitor] DM notification received. Type 10
info: Roblox: 2025-09-04T02:55:46.285Z,1.285639,9e3376c0,6,Warning [DFLog::DMNotificationMonitor] DM notification received. Type 10
info: app_interface$json: {"type":"will_handle_app_startup"}
debug: rbx.AppBridgeV2: nativeAppBridgeV2StartApp:
debug: rbx.AppBridgeV2: nativeAppBridgeV2StartApp: Same native window 0x4cc04498340. No need to do anything!

**Comment by Melan3000** [comment]
> > Im having the same issue too it just instantly closes whenever I open sober.
> > info: app: lifecycle: logging_started delta=1.0442620001267642ms info: app: app tag = s063-1872-x86_64-gnu info: app: os release: Fedora Linux info: app: lifecycle: update_flags_from_remote_manifest delta=51.563420000020415ms info: state: using manifest object: {"do_not_retain_swapchain":1,"r1":1,"rbx_texture_semantic":1,"u":1,"use_fast_etc2_vulkan":1} info: app: lifecycle: fs_init delta=130.752179000061ms info: app: using config: { "allow_gamepad_permission": false, "bring_back_oof": false, "close_on_leave": false, "discord_rpc_enabled": true, "enable_gamemode": true, "enable_hidpi": false, "fflags": { "FFlagExample": true }, "server_location_indicator_enabled": false, "touch_mode": "off", "use_console_experience": false, "use_libsecret": false, "use_opengl": false } info: app: lifecycle: check_security delta=1.6807750000152737ms info: app$json: {"product_name":"Swift SF314-59\n","product_version":"V1.09\n","type":"device_product_info"} info: app: lifecycle: core_runtime delta=0.08881899993866682ms info: app: lifecycle: app_core delta=7.760707000037655ms info: app: lifecycle: sdl_init delta=735.8032129998319ms info: app: trying video backend preference: wayland,x11 info: app: using video backend: wayland info: app: trying audio subsystem pulseaudio info: app: using audio subsystem pulseaudio info: app: lifecycle: global_window_init delta=104.45083800004795ms info: app: lifecycle: gamemode_init delta=73.17099700006656ms info: app: lifecycle: interface_init delta=39.80908799986355ms debug: JNIMain: TelemetryProtocol::setProcessTimeOverride: 1433 info: rbx.JNIRobloxSettings: Setting default app policy file: content/guac/defaultConfigs/GuacDefaultPolicy-GlobalDist.json info: Roblox: 2025-09-04T02:55:45.559Z,0.559709,1b29680,6 [FLog::AndroidGLView] nativeInitClientSettings info: Roblox: 2025-09-04T02:55:45.567Z,0.567755,1b29680,6 [FLog::Output] LoadClientSettingsFromLocal: "Do not use this file. Use "/home/melan3000/.var/app/org.vinegarhq.Sober/config/sober/config.json" instead. " info: Roblox: 2025-09-04T02:55:45.567Z,0.567789,1b29680,6 [FLog::Error] Error loading settings: [0: Invalid value.] settings size = 107 info: Roblox: 2025-09-04T02:55:45.569Z,0.569036,1b29680,6 [FLog::AndroidGLView] nativePostClientSettingsLoadedInitialization3 info: Roblox: 2025-09-04T02:55:45.580Z,0.580680,1b29680,6,Info [FLog::AppMemUsageStatus] 3698476798 info: Roblox: 2025-09-04T02:55:45.580Z,0.580778,1b29680,6 [FLog::ClientRunInfo] RobloxGitHash: 84a28ed938d4cf1fb961d5cf9164991e6870de0e info: Roblox: 2025-09-04T02:55:45.580Z,0.580792,1b29680,6 [FLog::ClientRunInfo] The base url is https://www.roblox.com/ info: Roblox: 2025-09-04T02:55:45.580Z,0.580800,1b29680,6 [FLog::ClientRunInfo] The channel is production info: Roblox: 2025-09-04T02:55:45.581Z,0.581369,1b29680,6,Critical [DFLog::Mimalloc] Mimalloc integration detected, settings: info: Roblox: 2025-09-04T02:55:45.581Z,0.581385,1b29680,6,Critical [DFLog::Mimalloc] mi_option_show_errors=1 info: Roblox: 2025-09-04T02:55:45.581Z,0.581391,1b29680,6,Info [DFLog::Mimalloc] mi_option_show_stats=0 info: Roblox: 2025-09-04T02:55:45.581Z,0.581396,1b29680,6,Info [DFLog::Mimalloc] mi_option_verbose=0 info: Roblox: 2025-09-04T02:55:45.581Z,0.581401,1b29680,6,Critical [DFLog::Mimalloc] mi_option_eager_commit=0 info: Roblox: 2025-09-04T02:55:45.581Z,0.581405,1b29680,6,Info [DFLog::Mimalloc] mi_option_arena_eager_commit=2 info: Roblox: 2025-09-04T02:55:45.581Z,0.581409,1b29680,6,Info [DFLog::Mimalloc] mi_option_purge_decommits=1 info: Roblox: 2025-09-04T02:55:45.581Z,0.581412,1b29680,6,Info [DFLog::Mimalloc] mi_option_allow_large_os_pages=0 info: Roblox: 2025-09-04T02:55:45.581Z,0.581416,1b29680,6,Info [DFLog::Mimalloc] mi_option_reserve_huge_os_pages=0 info: Roblox: 2025-09-04T02:55:45.581Z,0.581422,1b29680,6,Info [DFLog::Mimalloc] mi_option_reserve_huge_os_pages_at=-1 info: Roblox: 2025-09-04T02:55:45.581Z,0.581434,1b29680,6,Info [DFLog::Mimalloc] mi_option_reserve_os_memory=0 info: Roblox: 2025-09-04T02:55:45.581Z,0.581439,1b29680,6,Info [DFLog::Mimalloc] mi_option_deprecated_segment_cache=0 info: Roblox: 2025-09-04T02:55:45.581Z,0.581443,1b29680,6,Info [DFLog::Mimalloc] mi_option_deprecated_page_reset=0 info: Roblox: 2025-09-04T02:55:45.581Z,0.581447,1b29680,6,Info [DFLog::Mimalloc] mi_option_abandoned_page_purge=0 info: Roblox: 2025-09-04T02:55:45.581Z,0.581450,1b29680,6,Critical [DFLog::Mimalloc] mi_option_purge_delay=0 info: Roblox: 2025-09-04T02:55:45.581Z,0.581454,1b29680,6,Info [DFLog::Mimalloc] mi_option_deprecated_segment_reset=0 info: Roblox: 2025-09-04T02:55:45.581Z,0.581458,1b29680,6,Info [DFLog::Mimalloc] mi_option_eager_commit_delay=1 info: Roblox: 2025-09-04T02:55:45.581Z,0.581462,1b29680,6,Info [DFLog::Mimalloc] mi_option_use_numa_nodes=0 info: Roblox: 2025-09-04T02:55:45.581Z,0.581466,1b29680,6,Info [DFLog::Mimalloc] mi_option_disallow_os_alloc=0 info: Roblox: 2025-09-04T02:55:45.581Z,0.581469,1b29680,6,Info [DFLog::Mimalloc] mi_option_os_tag=100 info: Roblox: 2025-09-04T02:55:45.581Z,0.581474,1b29680,6,Info [DFLog::Mimalloc] mi_option_max_errors=32 info: Roblox: 2025-09-04T02:55:45.581Z,0.581478,1b29680,6,Info [DFLog::Mimalloc] mi_option_max_warnings=32 info: Roblox: 2025-09-04T02:55:45.581Z,0.581482,1b29680,6,Info [DFLog::Mimalloc] mi_option_deprecated_max_segment_reclaim=10 info: Roblox: 2025-09-04T02:55:45.581Z,0.581486,1b29680,6,Info [DFLog::Mimalloc] mi_option_destroy_on_exit=0 info: Roblox: 2025-09-04T02:55:45.581Z,0.581490,1b29680,6,Info [DFLog::Mimalloc] mi_option_arena_reserve=1048576 info: Roblox: 2025-09-04T02:55:45.581Z,0.581494,1b29680,6,Info [DFLog::Mimalloc] mi_option_arena_purge_mult=1 info: Roblox: 2025-09-04T02:55:45.581Z,0.581498,1b29680,6,Info [DFLog::Mimalloc] mi_option_deprecated_purge_extend_delay=1 info: Roblox: 2025-09-04T02:55:45.581Z,0.581502,1b29680,6,Info [DFLog::Mimalloc] mi_option_disallow_arena_alloc=0 info: Roblox: 2025-09-04T02:55:45.581Z,0.581507,1b29680,6,Info [DFLog::Mimalloc] mi_option_retry_on_oom=400 info: Roblox: 2025-09-04T02:55:45.581Z,0.581510,1b29680,6,Info [DFLog::Mimalloc] mi_option_visit_abandoned=0 info: Roblox: 2025-09-04T02:55:45.581Z,0.581515,1b29680,6,Info [DFLog::Mimalloc] mi_option_guarded_min=0 info: Roblox: 2025-09-04T02:55:45.581Z,0.581518,1b29680,6,Info [DFLog::Mimalloc] mi_option_guarded_max=1073741824 info: Roblox: 2025-09-04T02:55:45.581Z,0.581522,1b29680,6,Info [DFLog::Mimalloc] mi_option_guarded_precise=0 info: Roblox: 2025-09-04T02:55:45.581Z,0.581530,1b29680,6,Info [DFLog::Mimalloc] mi_option_guarded_sample_rate=0 info: Roblox: 2025-09-04T02:55:45.581Z,0.581538,1b29680,6,Info [DFLog::Mimalloc] mi_option_guarded_sample_seed=0 info: Roblox: 2025-09-04T02:55:45.581Z,0.581542,1b29680,6,Info [DFLog::Mimalloc] mi_option_page_reclaim_on_free=0 info: Roblox: 2025-09-04T02:55:45.581Z,0.581546,1b29680,6,Info [DFLog::Mimalloc] mi_option_page_full_retain=2 info: Roblox: 2025-09-04T02:55:45.581Z,0.581550,1b29680,6,Info [DFLog::Mimalloc] mi_option_page_max_candidates=4 info: Roblox: 2025-09-04T02:55:45.581Z,0.581555,1b29680,6,Info [DFLog::Mimalloc] mi_option_max_vabits=0 info: Roblox: 2025-09-04T02:55:45.581Z,0.581559,1b29680,6,Info [DFLog::Mimalloc] mi_option_pagemap_commit=0 info: Roblox: 2025-09-04T02:55:45.581Z,0.581563,1b29680,6,Info [DFLog::Mimalloc] mi_option_page_commit_on_demand=0 info: Roblox: 2025-09-04T02:55:45.581Z,0.581566,1b29680,6,Info [DFLog::Mimalloc] mi_option_page_max_reclaim=-1 info: Roblox: 2025-09-04T02:55:45.581Z,0.581570,1b29680,6,Info [DFLog::Mimalloc] mi_option_page_cross_thread_max_reclaim=32 info: Roblox: 2025-09-04T02:55:45.581Z,0.581857,1b29680,6,Info [FLog::AppMemUsageStatus] 923286370 info: device_params_impls$json: {"device_memory_class_mib":2048,"device_memory_mib":7722,"is_low_ram_device":false,"type":"memory_params"} info: rbx.AppBridgeV2: nativeAppBridgeAppStart_original: debug: rbx.AppBridgeV2: nativeAppBridgeV2Init: info: Roblox: 2025-09-04T02:55:45.593Z,0.593423,9f53b6c0,6 [FLog::SingleSurfaceApp] initializeWithAppStarter info: Roblox: 2025-09-04T02:55:45.593Z,0.593451,9f53b6c0,6 [FLog::SingleSurfaceApp] initializeSingleton info: Roblox: 2025-09-04T02:55:45.593Z,0.593641,9f53b6c0,6 [FLog::Output] setAssetFolder /home/melan3000/.var/app/org.vinegarhq.Sober/data/sober/assets/content/ info: Roblox: 2025-09-04T02:55:45.593Z,0.593718,9f53b6c0,6 [FLog::Output] setExtraAssetFolder /home/melan3000/.var/app/org.vinegarhq.Sober/data/sober/assets/ExtraContent info: Roblox: 2025-09-04T02:55:45.593Z,0.593808,9f53b6c0,6 [FLog::Output] Evaluating deferred inferred crashes info: Roblox: 2025-09-04T02:55:45.593Z,0.593936,9f53b6c0,6 [FLog::SingleSurfaceApp] registerForForceOTAUpdateAvailableConnection stage = 0 info: Roblox: 2025-09-04T02:55:45.595Z,0.595445,9f53b6c0,6 [FLog::DataModelPatchConfigurer] [_DataModelPatch] Load configs for user key: app:14169667683193958462 info: Roblox: 2025-09-04T02:55:45.595Z,0.595998,9f53b6c0,6 [FLog::SingleSurfaceApp] setStage: (stage:Native) info: Roblox: 2025-09-04T02:55:45.596Z,0.596016,9f53b6c0,6,Warning [FLog::SingleSurfaceApp] instantiate controllers info: Roblox: 2025-09-04T02:55:45.596Z,0.596022,9f53b6c0,6 [FLog::SurfaceController] SurfaceController[_:1]::SurfaceController, count: 1 info: Roblox: 2025-09-04T02:55:45.596Z,0.596028,9f53b6c0,6,Warning [FLog::SingleSurfaceApp] instantiate experience coordinator info: Roblox: 2025-09-04T02:55:45.596Z,0.596096,9f53b6c0,6,Info [DFLog::CoordinatorMemoryPressure] Setting memory pressure threshold to none info: Roblox: 2025-09-04T02:55:45.597Z,0.597486,9f53b6c0,6,Info [FLog::PerformanceControlUtil] PerformanceControlUtil: registered single surface tunable (id=0) info: Roblox: 2025-09-04T02:55:45.597Z,0.597510,9f53b6c0,6,Info [FLog::CrossExperienceVoiceController] CrossExperienceVoiceController::CrossExperienceVoiceController() constructor info: Roblox: 2025-09-04T02:55:45.597Z,0.597530,9f53b6c0,6,Info [FLog::PerformanceControlUtil] PerformanceControlUtil: registered single surface tunable (id=1) info: app: lifecycle: interface_start delta=346.06318400008604ms info: Roblox: 2025-09-04T02:55:45.597Z,0.597711,9f53b6c0,6 [FLog::SingleSurfaceApp] initializeLuaAppWithLoggedInUser: (stage:Native). info: Roblox: 2025-09-04T02:55:45.597Z,0.597719,9f53b6c0,6 [FLog::SingleSurfaceApp] applyLocale info: Roblox: 2025-09-04T02:55:45.609Z,0.609099,9f53b6c0,6 [FLog::DataModelPatchConfigurer] [_UniversalAppPatch] Load configs for user key: app:14169667683193958462 info: Roblox: 2025-09-04T02:55:45.609Z,0.609264,9f53b6c0,6 [FLog::DataModelPatchConfigurer] [_UniversalAppPatch] Retrieving patch info: Roblox: 2025-09-04T02:55:45.609Z,0.609274,9f53b6c0,6 [FLog::DataModelPatchConfigurer] getCachedPatch DataModelPatchConfig : type=1, assetId=118593852151835, assetVersion=3369, maxAppVersion=687, localAssetURI=rbxasset://models/UniversalApp/UniversalApp.rbxm info: Roblox: 2025-09-04T02:55:45.609Z,0.609284,9f53b6c0,6 [FLog::DataModelPatchConfigurer] getCachedPatch : numAttempts=10 info: Roblox: 2025-09-04T02:55:45.609Z,0.609327,9f53b6c0,6 [FLog::DataModelPatchConfigurer] getCachedPatch : contentId=rbxasset://models/UniversalApp/UniversalApp.rbxm info: Roblox: 2025-09-04T02:55:45.609Z,0.609334,9f53b6c0,6 [FLog::DataModelPatchConfigurer] getCachedPatch : get patch from content provider for Model info: Roblox: 2025-09-04T02:55:45.609Z,0.609380,9f53b6c0,6 [FLog::DataModelPatchConfigurer] deserializeAndVerifyPatch with blake3 info: Roblox: 2025-09-04T02:55:45.810Z,0.810816,9f53b6c0,6,Warning [DFLog::BootcampCLI161265Log] Hello world ...! info: Roblox: 2025-09-04T02:55:45.810Z,0.810851,9f53b6c0,6,Warning [DFLog::BootcampCLI158749Log] hey world info: Roblox: 2025-09-04T02:55:45.810Z,0.810857,9f53b6c0,6,Warning [FLog::Output] Hello world!!! info: Roblox: 2025-09-04T02:55:45.810Z,0.810863,9f53b6c0,6,Warning [DFLog::BootcampCLI149079Log] Hello world? info: Roblox: 2025-09-04T02:55:45.810Z,0.810868,9f53b6c0,6,Warning [DFLog::BootcampCLI154937Log] I love roblox. Roblox is life info: Roblox: 2025-09-04T02:55:45.810Z,0.810872,9f53b6c0,6,Warning [DFLog::BootcampCLI156010Log] Hello there, world info: Roblox: 2025-09-04T02:55:45.810Z,0.810877,9f53b6c0,6,Warning [DFLog::BootcampCLI162827Log] Hello world, this is the last time I onboard! info: Roblox: 2025-09-04T02:55:45.810Z,0.810881,9f53b6c0,6,Warning [DFLog::BootcampCLI161528Log] Hello folks~ info: Roblox: 2025-09-04T02:55:45.810Z,0.810885,9f53b6c0,6,Warning [DFLog::BootcampCLI163626Log] Hello world :) info: rbx.AppBridgeV2: nativeAppBridgeAppStart: StartupController finished starting: stage = 2, BTID = 0, upgradeStatus = 3. info: Roblox: 2025-09-04T02:55:45.819Z,0.819193,9f53b6c0,6 [FLog::SingleSurfaceApp] setStage: (stage:InitializedLuaApp) info: app: lifecycle: pre_main_loop delta=221.53582100011408ms info: app: lifecycle: enter_main_loop delta=0.007272999966517091ms debug: rbx.AppBridgeV2: nativeAppBridgeV2UpdateSurfaceApp: debug: rbx.AppBridgeV2: nativeAppBridgeV2UpdateSurfaceApp: Created ANativeWindow 0x4cc04498340 (ID:1) info: Roblox: 2025-09-04T02:55:45.822Z,0.822468,9f53b6c0,6 [FLog::SingleSurfaceApp] updateSurfaceLuaApp: (stage:InitializedLuaApp) info: Roblox: 2025-09-04T02:55:45.822Z,0.822489,9f53b6c0,6,Warning [FLog::SurfaceController] SurfaceController[_:1]::update. debug: rbx.AppBridgeV2: nativeAppBridgeV2UpdateSurfaceGameNew: debug: rbx.AppBridgeV2: nativeAppBridgeV2UpdateSurfaceGameNew: Same native window 0x4cc04498340. No need to do anything! info: Roblox: 2025-09-04T02:55:45.833Z,0.833513,9f53b6c0,6 [FLog::SingleSurfaceApp] updateSurfaceUGCGame: (stage:InitializedLuaApp). info: Roblox: 2025-09-04T02:55:45.833Z,0.833575,9e2366c0,6 [FLog::Output] Info: DataModel Loading rbxasset://places/Mobile.rbxl info: Roblox: 2025-09-04T02:55:45.850Z,0.850652,9e2366c0,6 [FLog::DataModelPatchConfigurer] OTAPollingEnabled set to: false info: Roblox: 2025-09-04T02:55:45.894Z,0.894056,9e2366c0,6 [FLog::DataModelPatchConfigurer] [discovery-ota] Load configs for user key: app:14169667683193958462 info: Roblox: 2025-09-04T02:55:45.894Z,0.894291,9e2366c0,6 [FLog::DataModelPatchConfigurer] [discovery-ota] Retrieving patch info: Roblox: 2025-09-04T02:55:45.894Z,0.894305,9e2366c0,6 [FLog::DataModelPatchConfigurer] getCachedPatch DataModelPatchConfig : type=1, assetId=16639814581, assetVersion=4918, maxAppVersion=687, localAssetURI= info: Roblox: 2025-09-04T02:55:45.966Z,0.966238,9e2366c0,6,Info [FLog::AudioFocusManager] AudioFocusManager::AudioFocusManager() constructor info: Roblox: 2025-09-04T02:55:45.966Z,0.966277,9e2366c0,6,Info [FLog::AudioFocusService] AudioFocusService::AudioFocusService() constructor info: Roblox: 2025-09-04T02:55:45.966Z,0.966287,9e2366c0,6,Info [FLog::AudioFocusService] AudioFocusService onServiceProvider invokation info: Roblox: 2025-09-04T02:55:45.966Z,0.966292,9e2366c0,6,Info [FLog::AudioFocusService] AudioFocusService::AudioFocusService() onServiceProvider setup info: app_interface$json: {"place_id":"0","type":"game_loaded"} info: Roblox: 2025-09-04T02:55:46.167Z,1.167887,9c9326c0,12 [DFLog::HttpTraceError] CURLINFO_OS_ERRNO: 111 Connection refused info: Roblox: 2025-09-04T02:55:46.167Z,1.167922,9c9326c0,12 [DFLog::HttpTraceError] CURLOPT_ERRORBUFFER: Failed to connect to localhost port 5051 after 2 ms: Could not connect to server info: Roblox: 2025-09-04T02:55:46.168Z,1.168074,9c1316c0,6 [DFLog::WebSocketTraceError] ws: 0 url: http://localhost:5051 error: HttpError: ConnectFail info: Roblox: 2025-09-04T02:55:46.168Z,1.168107,9c1316c0,12 [DFLog::HttpTraceError] HttpResponse([#4](https://github.com/vinegarhq/sober/issues/4) 0x7f27c13a06b0) time:2.7ms (net:2.6ms callback:0.0ms timeInRetryQueue:0.0ms) error:3 message:HttpError: ConnectFail url:{ "http://localhost:5051" } ip: external:0 numberOfTimesRetried:0 info: Roblox: 2025-09-04T02:55:46.172Z,1.172770,9e4386c0,6 [FLog::Warning] Warning: Unable to fetch completed survey ids from app storage info: Roblox: 2025-09-04T02:55:46.261Z,1.261088,9e2366c0,6,Warning [DFLog::DMNotificationMonitor] DM notification received. Type 10 info: Roblox: 2025-09-04T02:55:46.285Z,1.285639,9e3376c0,6,Warning [DFLog::DMNotificationMonitor] DM notification received. Type 10 info: app_interface$json: {"type":"will_handle_app_startup"} debug: rbx.AppBridgeV2: nativeAppBridgeV2StartApp: debug: rbx.AppBridgeV2: nativeAppBridgeV2StartApp: Same native window 0x4cc04498340. No need to do anything!
> 
> [#1280 (comment)](https://github.com/vinegarhq/sober/issues/1280#issuecomment-3251401358) <-- a quick workaround for the time being

I did the fix and it didnt work maybe i inputed the code wrong
{
    "allow_gamepad_permission": false,
    "bring_back_oof": false,
    "close_on_leave": true,
    "discord_rpc_enabled": true,
    "enable_gamemode": true,
    "enable_hidpi": false,
    "fflags": {
        "FFlagEnableDisplaySize9": true,
        "FFlagExample": true
    },
    "server_location_indicator_enabled": false,
    "touch_mode": "off",
    "use_console_experience": false,
    "use_libsecret": false,
    "use_opengl": false
}

**Comment by V3L0C1T13S** [comment]
Hiya everyone. This should be addressed fully now in the update we just pushed. Run `flatpak update` to try it out.

**Comment by szymonsz2903** [comment]
hi its not fixed i maneged to fix it by using a fflag and changing the config file to make it think its installed
