### ISSUE TITLE
Sober(Roblox) disconnecting after 2 minutes of play

### ISSUE THREAD

**Issue by tofiffeeeee** [vinegarhq/sober#977]
### Acknowledgement of checking existent issues

- [x] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

after downloading sober, I decided to go to play, everything was fine, but after 2 minutes of playing, the game disconnected me.
pop!_os linux

**Comment by hailhampter** [comment]
Even I'm facing the same issue. I've tried running `flatpak update` a few times, to see if there is an update fixing this issue, but even though there is an update, it still doesn't work.

**Comment by notakitaet** [comment]
also that problem on ubuntu 24.04.2

**Comment by V3L0C1T13S** [comment]
Fixed in 1.5.0. Run `flatpak update`.

**Comment by jakjasie1** [comment]
I'm having the same issue on 1.5.0. error log is spammed with "sendto failed with code -1 for char 1". and exit code on roblox is 277. trying to reconnect via the dialog throws error 769

**Comment by Kaden5480** [comment]
Can confirm as well, this is still happening on 1.5.0.

Lots of spamming with messages like `sendto failed with code -1 for char 1 and length 348.errno Address family not supported by protocol`.

Can also confirm the 277 and 769 error codes.

**Comment by V3L0C1T13S** [comment]
> Still happening on 1.5.0
> 
> But for me it only happens when im trying to open two sober instance at a time or trying to play on my kvm gpu passthrough setup.
> 
> They can both run fine for a few minutes, but randomly disconnects and spam `errno Address family not supported by protocol.`
> 
> And for the case where I'm using two sober instances, the instances opened later will always crash after a few minutes, but the one opened earlier will always run without problem.

Do keep in mind that both multi-instancing and VMs are not supported. You're free to try them, but this is more than likely not our bug in this case.

> Can confirm as well, this is still happening on 1.5.0.
> 
> Lots of spamming with messages like `sendto failed with code -1 for char 1 and length 348.errno Address family not supported by protocol`.
> 
> Can also confirm the 277 and 769 error codes.

Can you give more details on your setup and game logs?

**Comment by Kaden5480** [comment]
The system was running using QEMU/KVM with this info:
```
OS: Void Linux (x86_64-musl)
Kernel: 6.1.140_1
RAM: 24GB
CPU: 4 x Intel(R) Core(TM) i5-9600K (4) @ 3.69 GHz (only 4 of the total 6 have been passed through to VM)
GPU: AMD Radeon RX 6700 XT
NIC: Virtio
```
If you'd like anymore specific information about the system besides this, I can provide it.

Besides this one issue with disconnecting a couple of minutes after joining, it runs pretty well.

I have a log file for the entire runtime of when I was using sober. I read through it a bit and saw a few sections which are redacted. So I could upload the entire log file if it shouldn't have anything too sensitive in it and if that would be useful.

**Comment by Kaden5480** [comment]
> You might have luck following this hardening guide from VRChat: https://docs.vrchat.com/docs/using-vrchat-in-a-virtual-machine

This has allowed the game to run and stay connected for ~30 minutes. I haven't tested much further than this, but it seems to do the trick.

Thank you for the help.
